baseURL = 'https://doc.wnbgj.com/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = 'Tong Notes'
theme = 'stack'

# 版本号（用于 Docker 构建）
[params]
version = "1.0.0"

# 语言设置
[languages]
  [languages.zh-cn]
    languageName = "简体中文"
    contentDir = "content"
    weight = 1
    languageCode = "zh-cn"
    title = "Tong Notes"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true
      title = true