baseURL = 'https://doc.wnbgj.com/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = 'Tong Notes'
theme = 'stack'


[params]
version = "1.0.2"
description = "这是一个关于学习和研究新东西的记录笔记。"
favicon = "favicon.ico"
mainSections = ["posts"]
  [sidebar]
    [avatar]
    enabled = true
    local = true
    src = "img/avatar.jpeg"
  [article]
    toc = true
    math = true
    headingAnchor = true
    readingTime = true

# 语言设置
[languages]
  [languages.zh-cn]
    languageName = "简体中文"
    contentDir = "content"
    weight = 1
    languageCode = "zh-cn"
    title = "Tong Notes"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true
      title = true